version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aionz@123
      POSTGRES_DB: aionzdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
